export const intents = [
  {
    name: "greeting",
    section: null,
    keywords: [
      "halo",
      "hai",
      "hei",
      "hey",
      "hallo",
      "haloo",
      "selamat pagi",
      "selamat siang",
      "selamat sore",
      "selamat malam",
      "assalamu alaikum",
      "assalamualaikum",
      "permisi",
      "p",
      "pagi",
      "siang",
      "sore",
      "malam",
      "apa kabar",
      "hai bot",
      "halo bot",
    ],
  },
  {
    name: "help",
    section: null,
    keywords: [
      "bantuan",
      "bantu",
      "tolong",
      "menu",
      "apa yang bisa",
      "bisa apa",
      "fitur",
      "fungsi",
      "cara pakai",
      "cara penggunaan",
      "petunjuk",
      "panduan",
      "apa saja",
      "kemampuan",
      "kegunaan",
      "bisa ngapain",
      "apa yang kamu bisa",
      "kamu bisa apa",
    ],
  },
  {
    name: "school",
    section: "dashboard",
    keywords: [
      "sekolah",
      "profil sekolah",
      "profil",
      "smk",
      "smkn 1 karang baru",
      "smkn1 karang baru",
      "smk negeri 1",
      "smkn1",
      "smk 1",
      "smk karang baru",
      "karang baru",
      "kampus",
      "profil smk",
      "lembaga",
      "institusi",
      "madrasah",
      "smk negeri",
      "smkn",
      "sekolah apa",
      "sekolah siapa",
      "detail sekolah",
      "gambaran sekolah",
      "penjelasan sekolah",
      "deskripsi sekolah",
      "informasi lengkap sekolah",
      "riwayat sekolah",
      "sejarah sekolah",
      "latar belakang sekolah",
    ],
  },
  {
    name: "school_address",
    section: "dashboard",
    keywords: [
      "alamat",
      "alamat sekolah",
      "alamat smk",
      "lokasi",
      "lokasi sekolah",
      "lokasi smk",
      "letak",
      "letak sekolah",
      "letak smk",
      "dimana sekolah",
      "di mana sekolah",
      "dimana smk",
      "di mana smk",
      "alamat dimana",
      "sekolah dimana",
      "sekolah ada dimana",
      "sekolah berada dimana",
      "sekolah berlokasi",
      "berlokasi",
      "lokasi kantor",
      "kantor sekolah",
      "alamat kantor",
      "telp",
      "telepon",
      "nomor telepon",
      "nomor telpon",
      "no telp",
      "no hp",
      "nomor hp",
      "telpon berapa",
      "nomor berapa",
      "hubungi sekolah",
      "hubungi smk",
      "menghubungi",
      "cara menghubungi",
      "cara hubungi",
      "kontak",
      "kontak sekolah",
      "kontak smk",
      "nomor kontak",
      "email",
      "email sekolah",
      "email smk",
      "email berapa",
      "alamat email",
      "email address",
      "nomer kontak",
      "nomer telp",
      "jalan",
      "jl",
      "desa",
      "kabupaten",
      "aceh tamiang",
      "informasi kontak",
      "detail kontak",
    ],
  },
  {
    name: "school_vision",
    section: "dashboard",
    keywords: [
      "visi",
      "visi sekolah",
      "visi smk",
      "visi smkn",
      "visi smkn 1",
      "visi apa",
      "visi sekolah apa",
      "visi smk apa",
      "tujuan sekolah",
      "tujuan smk",
      "tujuan utama",
      "cita cita sekolah",
      "cita cita smk",
      "impian sekolah",
      "impian smk",
      "harapan sekolah",
      "harapan smk",
      "arah sekolah",
      "arah smk",
      "sasaran sekolah",
      "sasaran smk",
      "target sekolah",
      "target smk",
      "tujuan akhir",
      "visi misi",
      "visi dan misi",
      "visi saja",
      "mencetak lulusan",
      "mencetak",
    ],
  },
  {
    name: "school_mission",
    section: "dashboard",
    keywords: [
      "misi",
      "misi sekolah",
      "misi smk",
      "misi smkn",
      "misi smkn 1",
      "misi apa",
      "misi sekolah apa",
      "misi smk apa",
      "program sekolah",
      "program smk",
      "langkah sekolah",
      "langkah smk",
      "strategi sekolah",
      "strategi smk",
      "upaya sekolah",
      "upaya smk",
      "rencana sekolah",
      "rencana smk",
      "agenda sekolah",
      "agenda smk",
      "misi utama",
      "tujuan misi",
      "misi dan visi",
      "misi saja",
      "pembelajaran aktif",
      "kemandirian berwirausaha",
      "hidup sehat",
      "kerjasama industri",
      "kegiatan sekolah",
      "kegiatan utama",
      "program utama",
    ],
  },
  {
    name: "major",
    section: "dashboard",
    keywords: [
      "jurusan",
      "jurusan apa",
      "jurusan apa saja",
      "ada jurusan apa",
      "jurusan unggulan",
      "jurusan pilihan",
      "rpl",
      "pplg",
      "rekayasa perangkat lunak",
      "pengembangan perangkat lunak",
      "pengembangan perangkat",
      "perangkat lunak",
      "gim",
      "game",
      "game development",
      "program keahlian",
      "kompetensi keahlian",
      "bidang studi",
      "konsentrasi",
      "prodi",
      "pilihan jurusan",
      "teknik informatika",
      "informatika",
      "it",
      "teknologi informasi",
      "pengembangan game",
      "software development",
      "software",
      "coding",
      "pemrograman",
      "program komputer",
      "aplikasi",
      "keahlian apa",
      "keahlian sekolah",
      "spesialisasi",
      "fokus",
      "bidang unggulan",
      "program unggulan",
    ],
  },
  {
    name: "school_info",
    section: "dashboard",
    keywords: [
      "informasi sekolah",
      "info sekolah",
      "tentang sekolah",
      "profil lengkap sekolah",
      "pengetahuan sekolah",
      "gambaran sekolah",
      "deskripsi sekolah",
      "sekolah info",
      "sekolah informasi",
      "smk info",
      "smk informasi",
      "data lengkap sekolah",
      "informasi lengkap sekolah",
      "informasi detail sekolah",
      "sejarah singkat sekolah",
      "latar belakang singkat sekolah",
    ],
  },
  {
    name: "about",
    section: "tentang",
    keywords: [
      "tentang",
      "tentang kelas",
      "cerita",
      "cerita kelas",
      "kisah",
      "kisah kelas",
      "perjalanan",
      "perjalanan kelas",
      "sejarah",
      "sejarah kelas",
      "3 tahun",
      "tiga tahun",
      "riwayat",
      "riwayat kelas",
      "latar belakang",
      "asal usul",
      "kronologi",
      "rekam jejak",
      "jejak",
      "awal mula",
      "profil kelas",
      "kelas xii",
      "kelas xi",
      "kelas x",
    ],
  },
  {
    name: "learning",
    section: "tentang",
    keywords: [
      "pembelajaran",
      "fokus pembelajaran",
      "belajar",
      "materi",
      "materi pelajaran",
      "pelajaran",
      "kurikulum",
      "studi",
      "ilmu",
      "bidang belajar",
      "topik belajar",
      "fokus belajar",
      "mata pelajaran",
      "mapel",
      "kegiatan belajar",
      "metode belajar",
      "cara belajar",
      "pengajaran",
    ],
  },
  {
    name: "character",
    section: "tentang",
    keywords: [
      "karakter kelas",
      "sifat kelas",
      "kepribadian kelas",
      "ciri kelas",
      "ciri ciri kelas",
      "watak kelas",
      "budaya kelas",
      "kebiasaan kelas",
      "suasana kelas",
      "dinamika kelas",
      "iklim kelas",
      "kultur kelas",
    ],
  },
  {
    name: "members",
    section: "anggota",
    keywords: [
      "anggota",
      "member",
      "siswa",
      "daftar siswa",
      "daftar anggota",
      "kelas",
      "murid",
      "peserta didik",
      "pelajar",
      "teman kelas",
      "anak kelas",
      "list anggota",
      "list siswa",
      "semua anggota",
      "semua siswa",
      "siapa saja anggota",
      "siapa saja siswa",
      "data siswa",
      "data anggota",
      "nama nama siswa",
      "nama nama anggota",
    ],
  },
  {
    name: "member_query",
    section: "anggota",
    keywords: [
      "siapa",
      "siapakah",
      "profil",
      "profil lengkap",
      "info",
      "detail",
      "lengkap",
      "kenali",
      "kenal",
      "tentang siapa",
      "data diri",
      "biodata",
      "identitas",
    ],
  },
  {
    name: "member_attribute",
    section: "anggota",
    keywords: [
      "bio",
      "hobi",
      "hobinya",
      "hobby",
      "kesukaan",
      "kegemaran",
      "aktivitas",
      "role",
      "jabatan",
      "posisi",
      "kedudukan",
      "sifat",
      "karakter",
      "kepribadian",
      "watak",
      "minat",
      "bakat",
      "keahlian",
      "kemampuan",
    ],
  },
  {
    name: "member_prestasi",
    section: "anggota",
    keywords: [
      "prestasi member",
      "prestasi siswa",
      "prestasi anggota",
      "prestasi milik",
      "prestasi siapa",
      "capaian siswa",
      "capaian anggota",
      "capaian member",
      "pencapaian siswa",
      "pencapaian anggota",
      "penghargaan siswa",
      "penghargaan anggota",
    ],
  },
  {
    name: "prestasi",
    section: "prestasi",
    keywords: [
      "prestasi",
      "prestasi kelas",
      "daftar prestasi",
      "list prestasi",
      "semua prestasi",
      "pencapaian kelas",
      "juara",
      "lomba",
      "penghargaan",
      "kompetisi",
      "kejuaraan",
      "perlombaan",
      "turnamen",
      "olimpiade",
      "medali",
      "trofi",
      "piala",
      "sertifikat",
      "penghargaan kelas",
      "capaian kelas",
      "raihan kelas",
      "hasil lomba",
      "hasil kompetisi",
    ],
  },
  {
    name: "album",
    section: "album",
    keywords: [
      "album",
      "foto",
      "dokumentasi",
      "momen",
      "kenangan",
      "galeri",
      "gambar",
      "potret",
      "jepretan",
      "koleksi foto",
      "foto kelas",
      "foto bersama",
      "dokumentasi kelas",
      "arsip foto",
      "memorabilia",
      "liputan",
      "rekaman",
    ],
  },
  {
    name: "story",
    section: "dashboard",
    keywords: [
      "spotlight",
      "perjalanan kelas",
      "jejak waktu",
      "kelas selama 3 tahun",
      "kisah 3 tahun",
      "timeline kelas",
      "linimasa kelas",
      "tahapan kelas",
      "fase kelas",
      "periode kelas",
      "cerita 3 tahun",
      "narasi kelas",
      "kisah perjalanan",
      "momen kelas",
      "highlight kelas",
    ],
  },
  {
    name: "time",
    section: null,
    keywords: [
      "jam",
      "jam berapa",
      "pukul",
      "tanggal",
      "tanggal berapa",
      "waktu",
      "hari ini",
      "sekarang",
      "saat ini",
      "detik ini",
      "hari apa",
      "bulan apa",
      "tahun berapa",
      "waktu sekarang",
      "jam sekarang",
    ],
  },
  {
    name: "navigation",
    section: null,
    keywords: [
      "buka halaman",
      "buka bagian",
      "arahkan ke",
      "menuju halaman",
      "menuju bagian",
      "tampilkan halaman",
      "tampilkan bagian",
      "pindah ke",
      "scroll ke",
      "pergi ke",
      "navigasi ke",
      "ke halaman",
      "ke bagian",
      "lihat halaman",
      "lihat bagian",
      "akses halaman",
      "akses bagian",
      "tuju halaman",
      "tuju bagian",
    ],
  },
];

export const quickSuggestions = [
  "profil sekolah",
  "visi smk",
  "misi sekolah",
  "alamat sekolah",
  "jurusan rpl",
  "tentang kelas",
  "fokus pembelajaran",
  "karakter kelas",
  "daftar anggota",
  "siapa haliq",
  "bio haliq",
  "prestasi haliq",
  "siapa ketua kelas",
  "siapa wakil ketua",
  "prestasi kelas",
  "album foto",
  "perjalanan 3 tahun",
  "kontak sekolah",
];
